# Site settings
title: Ericteen Blog
header-img: img/home-bg-03.jpg
email: chengteen@163.com
copyright_name: Ericteen Blog
description: "Front-end engineer & UX designer"
baseurl: ""
url: "http://yourdomain.com"
weibo_username: 谟骁
github_username:  ericteen
zhihu_username:  谟骁
email_username:  chengteen@163.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
